
spring:
  profiles:
    active: dev
---
server:
  port: 3355
spring:
  profiles: dev
  application:
    name: cloud-config-client-dev
---
server:
  port: 3366
spring:
  profiles: test
  application:
    name: cloud-config-client-test