
spring:
  profiles:
    active: dev
---
server:
  port: 8011
spring:
  profiles: dev
  application:
    name: git-repository-file-dev
---
server:
  port: 8022
spring:
  profiles: test
  application:
    name: git-repository-file-test