server:
  port: 9527
spring:
  application:
    name: gateway-9527
  cloud:
    gateway:
      routes:
        - id: gateway
          uri: lb://provider
          predicates:
            - Path=/index
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/